name: Github Action demo
on: push
jobs:
  Action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: action/checkout@v6
      - name: printing the index.html file
        run: cat index.html

      
